### ISSUE TITLE
Add DiagnosticSeverity to the information of diagnostics

### ISSUE THREAD

**Issue by yaegassy** [volarjs/pug-language-tools#3]
In coc.nvim, there is a feature called "Sign" that displays and updates marks such as `>>` on lines with diagnostics.

**Example: volar**:

https://github.com/volarjs/pug-language-tools/assets/188642/6da4879a-4c4b-4262-8cca-a274c6fea51d

Signs are not displayed in `pug-language-server` because `DiagnosticSeverity` is not set in its diagnostics.

**Comment by johnsoncodehk** [comment]
Fixed in 1.1.2, thanks for the report!
